version: '3'
services:

  instagram_scraper:
    build: instagram_scraper/
    volumes:
    - ./instagram_scraper/:/app
    depends_on:
    - mongodb


  etl:

    build: etl/
    volumes:
    - ./etl/:/app
    depends_on:
    - mongodb



  mongodb:
    image: mongo
    ports:
    - 27017:27017

  # Optional for using Postgres docker container
  # postgresdb:
  #   image: postgres
  #   ports:
  #   - "5555:5432"
  #   environment:
  #   - POSTGRES_USER=postgres
  #   - POSTGRES_PASSWORD=1234
  #   - POSTGRES_DB=feedback
